repos:
  # ---------- Python ----------
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks: [ { id: black } ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks: [ { id: ruff } ]          # lint + isort replacement

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks: [ { id: mypy } ]          # type-checks backend

  # ---------- JavaScript / Vue ----------
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0                      # mirrors the latest ESLint 8.x
    hooks:
      - id: eslint
        files: "\\.(js|vue)$"
        args: [ "--fix" ]            # auto-fixes where possible

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: "\\.(js|vue|json|css|md)$"