name: lint-test
on: [ push, pull_request ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install deps
        run: |
          pip install pre-commit
          npm --prefix frontend ci

      - name: Run pre-commit (all files)
        run: pre-commit run --all-files
